{% set name = "usagestats" %}
{% set version = "0.7" %}
{% set sha256 = "39cf0736dfec40c85416270fc43382bdef7af18da85e1e243075f145fe2b8aef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python
    - requests

test:
  imports:
    - usagestats

about:
  home: http://github.com/remram44/usagestats
  license: Apache-2.0
  license_file: LICENSE.txt
  summary: 'Anonymous usage statistics collecter'
  description: |
    This package is meant to easily get usage statistics from the users of your
    program.

    Statistics will be collected but won't be uploaded until the user opts in.
    A message will be printed on stderr asking the user to explicitely opt in or
    opt out.
  dev_url: http://github.com/remram44/usagestats

extra:
  recipe-maintainers:
    - remram44
