travis:
  secure:
    BINSTAR_TOKEN: sJtyfgTrCuLtbrtMLoLdW0m8gfWoduigxS2SyuVxvHti7a7JXqijDVrqIZm1upqKOvsyWGUNApdLMAh4BxahWfdjk7DBIsgoDT6Lziz/0seHq/EFCIbQlQ4VJhDdA8trDX5VEP1Ev4XB+Hbv7k+OQtr6sFunvQmeObpiWkHtmQGjSinD9tOj3EfUPedUTDvSTdy1l49W3IMn8oq3Al7Tcy1lf8/MqZicsPfxibz0xootQC0CQ+aH5IcEwhTI2ZQG7oXUAxzZeUFG5Zh7pwfebnEIJBeOOLzkMj7s9zBUkstxpxsWwEUxjqyKpImHMxN2yn5vB0JWL62cf0ZcgMluSia3QZQz1xjmn/4qn78e14fEYS94ZLAOKM+KrIhtZBbdM1s/z8H3nwJwQ/qJrcwZhS3HD/n9waJf8odBxBcMp/cZ+9C795Y/qEFU2ncv2qOR2AjpTM6Ep0KWq+Vey1UyQvb5/1W8Uf7sOJWZF4at5B8XxLdAxr1tmAEDRVTIuEZRfBni6+kIOqox2PFmTE2gf5k4BhZp0nuoSssuEFG8mDYBktjnuWC+S56ni05BAzEhiBjEmlvir5MBDLzHNQ66fSWfPIWi8Ml9x4VmMVxC+V+39UDJAiQiT6qdDE7mfy3TJEQMTc6UmEDj+WT8qwB0vekBlkeKNUz8v9nQzBnFsF8=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
