travis:
  secure:
    BINSTAR_TOKEN: C/kXBd4sNgz+dy2Fhv7c2p5/jRS3ID+S/Dl3y+7oLW7FumDWu5idqjGxtDX0GPm823Gc5Ei3Ecvu+r6u+09pKo91cNSSgWPrjyo6kKzRzRRnO3jrtPVd238IlLBIRN0LjdZ1UIGsPjR9FdkM+nQO+qVY9PN0aDIYs4OhfnotSigdNgQLbGL9OINPeMOPt6dKBwC3LjlAaA6PScFbULqdve1D3E+DFc8LrIcQFjftL9fTQlyauhOfc3lMsOohoYyOQ1UFN58RRVCnoNIg/8M17W/ErLHkTxwc9PK1EZiIoKi/AMLSvClNy9EqBVd7F3NeF/9HqwA/GDwZxCAIajzQMfOt4AoAl9pFunuLsq98lfS7S6SZW6B+jyjQ5eRUyZZXEaFiEUlRfV1aB2QI0mCK9+RlsA+l4KWeYYfHEaGwOyCIcE6umRHwv4ymJAzPmJQ6HIWyTu0zZ3yMy4keLKixrba7t5o2u/22l286elcGVWjQCOHBRxpz33IUARCcTcTBmV8yk3dSdTepUuSKsj1O37MsUEjiLiPfYi7Hh2vnfFaUcoxods39puBu3RgtHVO1WnHMIZNAq96pBS8hgCDU/d0HcE5+ZMN4rbCHDfjhgfC/u27HGhxpbsemGnozmD6z6SnoSvSTBvy94FpdxYBl5JMfqWApMg+4UCOYyP8Pqns=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
